version: '3'

services:
  backend:
    build: .
    container_name: ota-backend-backend-1
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
    networks:
      - ota-network

  mongo:
    image: mongo:6.0
    container_name: ota-backend-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - apt_ota_system_mongo-data:/data/db
    restart: always
    networks:
      - ota-network

volumes:
  apt_ota_system_mongo-data:
    external: true

networks:
  ota-network:
    external: true
